name: "Pull request labeler"
on:
  workflow_dispatch:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - run: echo "prashant" > myrd.txt
    - name: ehcoed
      run: cat myrd.txt
  
  new:
    needs: triage
    runs-on: ubuntu-latest
    steps:
    - run: cat myrd.txt
