name: Manual Deployment

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      demo:
        description: random input
        type: string
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Hola
        if: ${{ inputs.demo != '' }}
        run: echo HOLA !!
