name: Checkbox

on:
  repository_dispatch:
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.client_payload.target_workflow == 'new1' 
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Hola
        run: echo New1 !!
