name: Checkbox

on:
  repository_dispatch:
  workflow_dispatch:
    branches:
      - main
    inputs:
      demo:
        description: random input
        type: choice
        default: "[ ] Item 1"
        options:
          - "[x] Item 1"
          - "[ ] Item 1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Hola
        run: echo HOLA !!
