name: Checkbox

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: 'Ther version to deploy'

concurrency:
  group: deploy-staging

jobs:
  from-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: List file
        run: ls

      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: 'hola2'
      
      - name: List file
        run: sleep 100000
