name: Promote SIT to STG

on:
  workflow_dispatch:

jobs:
  promote-stg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    
    - name: install requirements
      run: |
        pip install pyyaml
    
    - name: promoteToEnv.py SIT to STG
      run: |
        import os
        import yaml
    
